In [2]:
import sys
sys.version

'3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]'

In [3]:
import numpy as np
np.__version__


'1.24.1'

### Simple Neuron
Neuron computes the product of inputs and weights and add the bias to it and returns the output

In [17]:
inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1.0]
bias = 2

In [18]:
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2]
output = output + bias
print(output)

2.3


In [31]:
inputs_array = np.array(inputs)
weights_vector = np.array(weights)
output_vector = np.dot(inputs_array,weights_vector.T) + bias
print(output_vector)

4.8


### Single Layer
A layer computes the product of corresponding inputs and weights and add the corresponding bias to it and returns the output containing an array of output values

In [32]:
inputs_array = np.array([1,2,3,2.5])

weights1_vector = np.array([0.2,0.8,-0.5,1.0])
weights2_vector = np.array([0.5,-0.91,0.26,-0.5])
weights3_vector = np.array([-0.26,-0.27,0.17,0.87])

bias1 = 2
bias2 = 3
bias3 = 0.5

output1 = np.dot(inputs_array,weights1_vector.T) + bias1
output2 = np.dot(inputs_array,weights2_vector.T) + bias2
output3 = np.dot(inputs_array,weights3_vector.T) + bias3

output = [output1,output2,output3]
print(output)

[4.8, 1.21, 2.385]


In [33]:
weights_vector = np.array([[0.2,0.8,-0.5,1.0],
                           [0.5,-0.91,0.26,-0.5],
                           [-0.26,-0.27,0.17,0.87]])
                          
bias_vector = [2,3,0.5]
output_vector = np.dot(inputs_array,weights_vector.T) + bias_vector
print(output_vector)

[4.8   1.21  2.385]


What if inputs is a matrix instead of an array. 

In [34]:
inputs_vector = np.array([[1,2,3,2.5],[2.0,5.0,-1.0,2.0],[-1.5,2.7,3.3,-0.8]])

output_vector2 = np.dot(inputs_vector,weights_vector.T) + bias_vector
print(output_vector2)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
